### ISSUE TITLE
Intel Xeon ES QHZF/QHVC E5 2660V4

### ISSUE THREAD

**Issue by Helckare** [BIOS-iEngineer/HUANANZHI-X99-F8#11]
Hello!
I found myself in a difficult situation.
I bought HUANANZHI X99 F8 and Intel Xeon ES QHZF / QHVC E5 2660V4.
The seller said that this will not work, the motherboard BIOS does not support this processor.
Can you help me?

**Comment by BIOS-iEngineer** [comment]
Hello!
Sorry, the cost of work and the difference in price between the final processor are disproportionate.
