### ISSUE TITLE
Intel RST

### ISSUE THREAD

**Issue by avsroot** [BIOS-iEngineer/HUANANZHI-X99-F8#12]
Hello, after flashing new bios on F8, raid 0 not work properly, windows doesn't recoznize it, i can't configure raid under bios, where i should create or manage raid?

**Comment by BIOS-iEngineer** [comment]
Hallo! This was due to the difference of efi drivers. you can return the 26th version or wait some time before the release of the 28th version.

**Comment by avsroot** [comment]
Ok clear, but another question is how properly configure or create raid? ctrl + i seems not work in uefi, in bios not shown rst or im not look well
