### ISSUE TITLE
Do you could indicate me, what programer device to buy? 

### ISSUE THREAD

**Issue by GHM-0** [BIOS-iEngineer/HUANANZHI-X99-F8#13]
HELLO, WHAT EQUIPMENT (programer device) DO I BUY, To record this bios (without removing it, if possible) - I don't know anything about electronics

I'm looking for a technician, but 3 have already refused to work with this model. (I don't know why?)

Can you tell me where the chip is physically located, and how to access it?

I had a problem, when finally (update bios to latest version CX99DE28), Windows give me a blue screen ) and now I'm completely desperate! I'll no more trust in windows to flash bios any more

**Comment by BIOS-iEngineer** [comment]
![Screenshot_2021-01-25-20-17-09](https://user-images.githubusercontent.com/69295506/105740594-631d1100-5f4a-11eb-8ff8-6a05d7306b01.jpeg)
25Q128
No problem for update firmware with any programmer device., use e.g. EZP2019, CH341, (if you need make updates without solder supplement the kit with a special terminal for the programmer device - ask the seller)
You should give more attention to the description next time.

**Comment by GHM-0** [comment]
Thank you very much for answer,  I''will be less displicent next time, i've
got a doubt about this plastic cover(HUANANZHI logo)

Can I just pull or is it stuck to something? I'm very afraid of physical
damage!

And I never had made it before

Em seg., 25 de jan. de 2021 às 14:24, BIOS-iEngineer <
notifications@github.com> escreveu:

**Comment by BIOS-iEngineer** [comment]
It needs to be unscrewed from the back side of the board
