### ISSUE TITLE
RAID doesn't boot anymore?

### ISSUE THREAD

**Issue by GHM-0** [BIOS-iEngineer/HUANANZHI-X99-F8#14]
Hello I'm finally using CX99DE28 (seems very clean)

Well RAID doesn't seem to work (to BOOT), the disks in the array and any other in RAID [ SATA ports] 

Do you know any way to circumvent this unexpected behavior?

grub don't find disk anymore (by uuid or by label)
Windows also doesn't boot (In RAID mode)  // It was booting O.k
but array disks are mounted with live USB? // I just don't understand 

Could it be by suppression of CSM?

sudo dmesg | grep AHCI
[    1.141049] ahci 0000:00:11.4: AHCI 0001.0300 32 slots 4 ports 6 Gbps 0xc impl SATA mode
[    1.152472] ahci 0000:00:1f.2: AHCI 0001.0300 32 slots 4 ports 6 Gbps 0xf impl RAID mode

I believe that are the same errors in last version Bios Update from vendor (RAID was booting O.k)

 sudo dmesg | grep Error
[    0.751839] RAS: Correctable Errors collector initialized.
[    1.502042] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT1._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.502076] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT1._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.502170] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT3._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.502195] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT3._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.502257] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT0._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.502274] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT0._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.502361] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT2._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.502386] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT2._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.502962] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT2._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.502979] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT2._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.503056] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT3._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.503077] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT3._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.503140] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT1._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.503165] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT1._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    1.503551] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SAT1.SPT0._GTF.DSSP], AE_NOT_FOUND (20200528/psargs-330)
[    1.503577] ACPI Error: Aborting method \_SB.PCI0.SAT1.SPT0._GTF due to previous error (AE_NOT_FOUND) (20200528/psparse-529)

Ps.: Lenovo's logo (I had a heart attack, all my blood cold)
There is any way to customize, replacing that logo by another?

Thank you!

**Comment by BIOS-iEngineer** [comment]
Hi, You can use a disk for boot without RAID 😉
The fact is that HUANANZHI didn't make a logo for BIOS. To change the logo there is a description and necessary files in the text of the description on the motherboard page. You can also online search for information to change the logo for Aptio V BOISes. It's easy!

**Comment by GHM-0** [comment]
Oh sorry, boot itself is not on RAID, Boot menu doesn't show any disk in
RAID.

My Configuration:

[SSATA = AHCI]      //SATA II          [SATA = RAID]          //ALL SATA
III
[Home + Boot]       [FREE]              [Array Member1]      [Windows 10
+Rec + Boot]
[iTunes]                 [FREE]              [Array Member2]      [Media
Disk]

Do you have on your machine that errors (in bios) that I had previously
posted? Or that is way to circumvent, like disable some option in bios?

 I Will try make a fresh install in AHCI mode (and soft RAID is BACK)



Em qui., 4 de fev. de 2021 às 13:21, BIOS-iEngineer <
notifications@github.com> escreveu:

**Comment by BIOS-iEngineer** [comment]
Hi! Many people forget to use the 'donate' button, so I don't have much SSD for full test. But I know that other users have a RAID array working.
