### ISSUE TITLE
BIOS question 

### ISSUE THREAD

**Issue by DimaVIII** [BIOS-iEngineer/HUANANZHI-X99-F8#17]
Hey sorry about this, maybe unrelated but I have a issue with F8D motherboard which is mostly like F8.
I’m trying to add a Wifi card to the „sata m.2 ngff“ slot but the system does not recognize the card in this slot. If I put it into the NVMe slots it works. 
I can’t find any information on this „sata m.2 ngff“ slot and what it actually does. Do you have any clue if there is a switch in the BIOS as this dip switches seem not to work.

**Comment by BIOS-iEngineer** [comment]
Hi., If you buy me a X99-F8D motherboard and pay a small portion of the time that I spend, I'll make a BIOS for X99-F8D motherboard, which BIOS will work with all ports.

It is not wise to use bios from another motherboard and hope that everything work will with your motherboard.
