### ISSUE TITLE
how to toggle CSM and some issue

### ISSUE THREAD

**Issue by fallenlonelie** [BIOS-iEngineer/HUANANZHI-X99-F8#18]
I can not find menu to toggle csm.
And I use to SAPPHIRE Radeon RX 590 NITRO+ Special Edition OC D5 8GB Dual-X, DP by single display.
But black screen while booting is in progress.
It's normally turn on screen after boot OSes.
Any have solutions?

**Comment by BIOS-iEngineer** [comment]
https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8/issues/10

**Comment by fallenlonelie** [comment]
That's not for me.

I already flashed CX99DE28 (on W25Q128JVSSIQ, verified write OK).
And factory original rom on RX 590 & switched to 1.

It's raised same issue another HIS RX580 4GB OC on 2 eachs.

All I had radeons be shown boot screen on GIGABYTE H370M-D3H and GIGABYTE B85M-DS3H, GIGABYTE B75M-D3H, even X99-F8 on original rom.

**Comment by BIOS-iEngineer** [comment]
These BIOS don't have support legacy CSM, look for a problem in the graphics card or monitors or other solutions., You don't describe what happens to your equipment. This is not the fault of the BIOS, as other configurations are working or have been fixed in the graphics card.

**Comment by fallenlonelie** [comment]
doesn't any changed anything.
it just changed BIOS ROM to CX29DE28.
even almost same bios configurations to original bios.
(diffrent for just one, it's can't find set to CSM Disable)
works great radeon after boot Windows 10, macOS.
it's problem blank screen on while booting.
anyway, i'll keep looking for other solutions. thx.

**Comment by BIOS-iEngineer** [comment]
CSM permanently disabled., don't worry, any these BIOS compatible for Unix & Windows operation systems., Best compatibility for Installation latest version macOS.
