### ISSUE TITLE
External Programmer necessary for flash?

### ISSUE THREAD

**Issue by sam-semillia** [BIOS-iEngineer/HUANANZHI-X99-F8#19]
Hi,

is an external programmer necessary for the flash, or can I just do the same as with the original bios and flash via FPT.exe?

Thanks, 
BR

**Comment by BIOS-iEngineer** [comment]
Hi, You need read description.
![Screenshot_2021-05-05-22-35-59](https://user-images.githubusercontent.com/69295506/117199013-5eda7c80-adf2-11eb-8764-4438e49c2bff.jpeg)
