### ISSUE TITLE
Code error Ad and bip 5 

### ISSUE THREAD

**Issue by Dascx31** [BIOS-iEngineer/HUANANZHI-X99-F8#20]
hello after flash bios I have an error message Ad on the motherboard and I no longer display how to correct this problem thank you

**Comment by Dascx31** [comment]
Version CX99DE28

**Comment by BIOS-iEngineer** [comment]
Hi, if you update the firmware according to the description, there is no error.
Read the description carefully and try to update the firmware again.

**Comment by Dascx31** [comment]
I want to try to update my again how? I don't have a display

**Comment by BIOS-iEngineer** [comment]
But this implies the use of a programmer device

**Comment by Dascx31** [comment]
Is hard?  how to apply?

**Comment by BIOS-iEngineer** [comment]
What do you mean?

**Comment by Dascx31** [comment]
I would like to try to reinstall the bios knowing that I do not have a display to access the bios what can I do? sorry for my bad english i'm french

**Comment by BIOS-iEngineer** [comment]
You must use a programmer device, e.g. EZP2019, CH341 and other.... Never use software method to update firmware for Chinese motherboards. What graphics card is used in your system?

**Comment by Dascx31** [comment]
oh ok i have gtx 770

**Comment by BIOS-iEngineer** [comment]
This should work, the error occurred due to a software method firmware update. You need to fix it with programmer device

**Comment by Dascx31** [comment]
Ok thks you i need another pc and is it ok?

**Comment by BIOS-iEngineer** [comment]
😄 But that's what everyone does., or have spare chips with BIOS.

**Comment by Dascx31** [comment]
no but I know its but suddenly I have to change the bios chip: o 
there is no alternative solution if yes I would like to know

**Comment by Dascx31** [comment]
step by step

**Comment by BIOS-iEngineer** [comment]
Only the programmer device!
