### ISSUE TITLE
Error code “Ad”

### ISSUE THREAD

**Issue by Vili1** [BIOS-iEngineer/HUANANZHI-X99-F8#21]
Hello, I flashed the latest bios version using fpt64 it said that the flashing process was successful so I restarted my pc and then it started beeping and it gave me a D6 code so I did some research and I found the other opened issues with that error so I decided to try a different video card and I changed my current old Radeon card for an old nvidia Quadra card and it’s still beeping like that but this time it gives me error code Ad and there isn’t any display signal , I know that u recommend using a usb programmer and stuff but is there any other way to fix my issues? Like remote connection or something or the Ad code is still related to my video card since I have no video output. I also tried to remove the cmos battery but still nothing.

**Comment by BIOS-iEngineer** [comment]
Use the programmer device as described in the instructions ⚠️⚠️⚠️

**Comment by Vili1** [comment]
@BIOS-iEngineer alright I used a flash programmer but no success either , my motherboard has “ winbond 25q128jvsq” bios chip and I used CH341A programmer but this time is giving me a different error code B7 , I removed the cmos battery but still the same issue
