### ISSUE TITLE
Error code AD after flashing with a programmer 

### ISSUE THREAD

**Issue by Vili1** [BIOS-iEngineer/HUANANZHI-X99-F8#22]
I tried different video cards like Radeon hd 3800 series , Radeon firepro s9010 and an old quadro from nvidia , also I’m very sure that the flashing was successful by dumping the bios and doing a checksum and I made sure to clear the cmos as well

**Comment by BIOS-iEngineer** [comment]
The description says that the legacy graphics cards are not supported. ⚠️

**Comment by Vili1** [comment]
@BIOS-iEngineer is there a way to re enable the legacy support ? , the thing is that my xeon e5-2698 v4 isnt turbo boosting properly with the original bios , i will pay if the price is acceptable
