### ISSUE TITLE
Question about compatibility with another motherboard (F8 and T8)

### ISSUE THREAD

**Issue by snookilow** [BIOS-iEngineer/HUANANZHI-X99-F8#24]
Hello! I have a question, can your BIOS be used for HUANANZHI-X99-T8? Will RAM slots work with DDR3? F8 and T8 are they compatible? Will your BIOS not damage my board?

**Comment by BIOS-iEngineer** [comment]
All my programs for the programmer device, you can find out for yourself. If you don't have a programmer, I can't help you.
