### ISSUE TITLE
Mobo dead

### ISSUE THREAD

**Issue by mgscreativa** [BIOS-iEngineer/HUANANZHI-X99-F8#26]
Hi! I programmed the BIOS with CX99DE28 and CH341A programmer and all went right. After a few seconds, I saw the lenovo logo but then the PC went off and now it wont turn on again. Do you know what could happen?

Will try to re program to see what appens

Thanks!

**Comment by BIOS-iEngineer** [comment]
In some cases, it is required to reset the Power Good signal (Due to the lack of standardization on the part of the motherboard manufacturer)

**Comment by mgscreativa** [comment]
Done... removed CMOS batt, power cable and accessed the BIOS ans applied Load Defaults then save and exit as per instructions but now I have another issue. Filling new issue for that to keep things clear

**Comment by mgscreativa** [comment]
Hi! just stopped by to let you know taht everything is working just fine. Before flashing the BIOS with yours, I have taken pictures of every stock BIOS config, and after flashing, setting almos all that parameters back did the trick to get me on going. Thanks for the BIOS it's great!

**Comment by BIOS-iEngineer** [comment]
Good for you!

**Comment by mgscreativa** [comment]
Hi! Just sent you a PR that improves the Readme of the project. Hope you like it.
