### ISSUE TITLE
Error 26

### ISSUE THREAD

**Issue by D7FoLT** [BIOS-iEngineer/HUANANZHI-X99-F8#3]
I flashed your BIOS to the motherboard HUANANZHI-X99-F8.
I decided to make a backup, but it gives me an error "Error 26: The host CPU does not have read access to the target flash area. To enable read access for this operation you must modify the descriptor settings to give host access to this region."
Earlier, after flashing with other BIOS versions, this problem did not exist.
How to remove protection on your BIOS?

**Comment by BIOS-iEngineer** [comment]
That's impossible
