### ISSUE TITLE
ECC support x99-rs9 bios

### ISSUE THREAD

**Issue by MdcNa** [BIOS-iEngineer/HUANANZHI-X99-F8#31]
hi, is there any bios for x99-RS9 which supports ECC? Could you possibly give me a hand to modify the current bios?

**Comment by BIOS-iEngineer** [comment]
no problem, sponsor the board and development

**Comment by MdcNa** [comment]
In which way?

**Comment by BIOS-iEngineer** [comment]
you can send the board by mail, or buy from China, if you are not from the European Union then the additional costs are covered by €100
