### ISSUE TITLE
I cant flash back to my original bios

### ISSUE THREAD

**Issue by cbuosi** [BIOS-iEngineer/HUANANZHI-X99-F8#4]
After flashing , I cant flash back to my original bios:

Intel (R) Flash Programming Tool. Version:  9.1.10.1000
Copyright (c) 2007 - 2014, Intel Corporation. All rights reserved.

Platform: Intel(R) C610 Series Chipset
Reading HSFSTS register... Flash Descriptor: Valid

    --- Flash Devices Found ---
    W25Q128BV    ID:0xEF4018    Size: 16384KB (131072Kb)

Error 26: The host CPU does not have read access to the target flash area. To enable read access for this operation you must modify the descriptor settings to give host access to this region.

**Comment by BIOS-iEngineer** [comment]
```
How to update Firmware:
1) Burn the Firmware to programmer device. (e.g. EZP-2019)
```
You now can overwrite only BIOS area, without ME firmware. If you can't have programmer device.
