### ISSUE TITLE
Legacy boot doesn't work

### ISSUE THREAD

**Issue by eugene159** [BIOS-iEngineer/HUANANZHI-X99-F8#5]
I tried pretty much everything - it just doesn't boot from hard drives or USB flash drives that are formatted for legacy boot.
UEFI boot works fine.
Is it fixable ?

**Comment by BIOS-iEngineer** [comment]
legacy is not supported

**Comment by eugene159** [comment]
You probably need to mention this in the description. Since broken legacy boot is a deal breaker for the most of users.

**Comment by BIOS-iEngineer** [comment]
you can carefully watch the description and picture, there is no legacy to boot
