### ISSUE TITLE
CX99DE26 10/10/2020  bug

### ISSUE THREAD

**Issue by szkifen** [BIOS-iEngineer/HUANANZHI-X99-F8#6]
CX99DE26 10/10/2020  

Will occasionally blue screen of death

CX99DE25
Everything is normal, no blue screen of death

X99-F8    I75820K  32G DDR4 2400   。

**Comment by BIOS-iEngineer** [comment]
I don't know what you're doing to get the 'blue screen of death'

**Comment by BIOS-iEngineer** [comment]
Very soon I'll make an addition CX99DE27 and you'll check again. This was about fixing the 'double boot menu'. Now it's being tested, but it's never been BSOD
