### ISSUE TITLE
It's compatible with version 2.0 of the Motherboard?

### ISSUE THREAD

**Issue by GHM-0** [BIOS-iEngineer/HUANANZHI-X99-F8#9]
Hi, I have a question this version can be used on version 2.0 of the motherboard, I am currently using the latest version provided by the manufacturer (http://www.huananzhi.com:8080/driversdownload/X99-F8Drive/X99-F8BIOS20-8-17.rar (G3X99904)), It seems to have a lot of errors, the linux logs are crazy, I've tried to restore the original version but the errors persisted (maybe these error were already there (always), but I haven't seen these before), May I use CX99DE26.BIN or it's not compatible, (fptw64 -f CX99DE26.BIN/ on windows)
It Has some way to test compatility?

I really don't know if this message should be send here as issue? probabily not, but it's my first time using GITHUB - Sorry

**Comment by BIOS-iEngineer** [comment]
You better use version CX99DE25 or CX99DE26. Use the programmer device to update the firmware! it helps to get rid of bugs in 90% of cases.

**Comment by GHM-0** [comment]
Thanks for the answer, I will try soon as possible!

**Comment by speedyb0y** [comment]
Hi, sorry to bother you, but I didn't want to open a new "issue" on your project just to ask this.

I flashed the CX99DE27.BIN file on my BIOS; the machine is still working.

1) I was expecting that cool REPUBLIC OF BELARUS boot image.
But instead, now my chinese board became a LENOVO lols
Is this correct?

2) I know you tell to flash using a programmer device. I used FLASHROM (on Linux).
But now I can't restore my previous BIOS, as the tool now complains that part of the flash is protected by Intel ME (I didn't know about it before... so it means that now I have some software running on my machine which can do anything it wants and I have no access to it? 😭️😭️😭️😭️)

I was using a BIOS from https://github.com/miyconst/Mi899 , and didn't have this problem (also flashed with FLASHROM).

3) Is there any way to get turbo unlock with your BIOS?
You are using the latest microcode... does it mean the turbo unlock is not possible? :(

**Comment by speedyb0y** [comment]
@GHM-0 how can I find out which board version I'm using?

I think mine is a recent one; I bought on august and my original BIOS was from 2020, but I don't know the BIOS version now.

What problems are you facing on Linux?

I have too many errors while trying to use my "SSATA" ports (the 4 connectors on the left).
One of my SSDs died while I tried to install on this board.
Trying to use them is too risky because the problem kicks in randomly and I almost lost precious data.

Now I don't know if my board is defective, or if this is a problem with the model itself - everyone else is use Windows so I can't trust when they say "everything is fine" as they don't have a "dmesg" command to know what is going on!

**Comment by speedyb0y** [comment]
@GHM-0  by the way if you intend to use the board for high performance and unlock turbo mode, there are some tricks to make it work on Linux.

You must compile the kernel with some specific options and pass the "idle=poll" argument.

I can post my config as soon as I fix the current mess here.

**Comment by BIOS-iEngineer** [comment]
@GHM-0 Hi! For use 'REPUBLIC OF BELARUS' boot screen you need download & replace (e.g.UEFIToot _0.28)_ file _GUID 7BB28B99-61BB-11D5-9A5D-0090273FC14D.ffs-_ as described below.

ME Region & Descriptor is blocked in accordance with security requirements. BIOS Region is free.

If you want to make 'unlock' you must remove the microcode and continue to act on the instruction. Use the software recommended for all actions and described by the instruction. After modification BIOS use _AfuEFIx64.efi_ as described below.

**Comment by GHM-0** [comment]
It's Original Bios Version was from 2019, you can see its version of the
board (printed in it)

I'm been experiencing some Storage error in RAID 0 in SSATA , in the first
time that I had used it was no errors beacuse disks were in (SoftRAID0) and
controller in EHCI mode

I bought 2  New HDDs (Wester digital - that green ones) , so I thinked why
not RAID0 by Hardware and the problem beggins

First I was thinking that was an error in Kernel (same kind of DMA buffer
overflow) !Mitigations?  | I could not find no corelation about it, forum,
lists - I've discard this option

After I discover that idle3 (Western Digital)= (Part of the problem but not
its cause)

After n seconds disk reduce power consumption (spinning slowly)
By some motivation its cause a semble difference in BUS ATA

// I've Fixed it  by using idle3tool      // 80% resolvido no freezing any
more

What I know now!, First configuring SSATA to RAID will cause some kind of
error in BUS if SATA  is in EHCI mode

In my case I also have disks on EHCI(SATA) mode and not so new 2 of those
are SATA 2  (iTunes, Home) and System + Games are in SSATA(RAID)

// Now myboard is with default Bios, I've been test
BIOS-iEngineer/HUANANZHI-X99-F8 (but at this time) I've had choose to
continue with default (because of a Legacy  Graphics Card)
Seems not work with BIOS-iEngineer/HUANANZHI-X99-F8, I had to boot to
windows 10, because i couldn't start linux or see the bios setup

I've not Tested to put all disks to RAID, but when all disk are in EHCI
mode dmesg does't show any kind of disks error

//Sorry about any error, I'm dislexic and not native english speaker

Em seg., 18 de jan. de 2021 às 20:07, Willian B. <notifications@github.com>
escreveu:

**Comment by speedyb0y** [comment]
// 80% resolvido

engasguei com o feijão quando li essa parte

tu também é brasileiro? kkkkkkkkk

**Comment by speedyb0y** [comment]
Sinceramente, relacionado a essas portas SSATA, eu desisti... estes erros acontecem com todas as configurações que tento na BIOS, já tentei usar 3 BIOS diferentes, é o mesmo tanto com HD quanto SSD etc

placa mãe com 8 portas SATA, das quais só 4 dá para usar, sendo que tenho 10 HDs com arquivos para processar 


O único problema que está tendo aí é com o SSATA?
Se for isso, parece que não tem jeito... já perguntei em canal do youtube e todos falaram que a deles FUNCIONA, mas todo mundo lá usa rWindows então eu acho que eles devem estar com o mesmo problema e nem sabem disso...

Mas quanto a tua placa de vídeo só funcionar com a BIOS original, deve ser algo em relação ao UEFI...
Para usar o turbo mode tem que usar essa BIOS modificada, e ela só roda em modo UEFI, teoricamente era para funcionar até em placa de vídeo antiga... aqui funcionou com uma NVS 310 (não sei de quando ela é mas é DDR3 kkk)
e com uma NVIDIA 1080 TI também funcionou sem problemas

**Comment by GHM-0** [comment]
Acontece com todo mundo (num ri po)

Nesse momento meu maior erro é ter acreditado que dava pra gravar a bios
apartir do windows (procurando um serviço para gravar essa bios nova)

O problema do SSATA acontecia toda vez, que aparentemente (idle3) rodava,
dava pra ver no log a tentativa de renegociar a velocidade (indo e
voltando), o que não fazia sentido já que os discos no RAID erram todos
sata3 (todas as portas), seguida de erro de I/O, bom o erro parou de
acontecer, embora também tenha recentemente invertido a ordem (SSATA - to
AHCI) (SATA- to RAID) pela logística de espaço pros cabos

A sobre os 20% que não resolvi ainda, é sobre o gerenciamento de energia do
SATA,  ALPM
se for desativado o desempenho cai sensivelmente (é só deixar ativado -OK
(eu sei))

Como está a configuração? SSATA | SATA

eu tenho mais vergonha de ter trocado (AHCI) por EHCI(usb2.0) // nada haver
pura viajem

Me preparando pra tomar uma facadinha, na regravação da bios - that's all
folks

Ps.: O problema no SSATA era do gringo! ( to de boa)





Em qua., 20 de jan. de 2021 às 21:59, Willian B. <notifications@github.com>
escreveu:
